### ISSUE TITLE
UCI

### ISSUE THREAD

**Issue by SzotsGabor** [JoAnnP38/Pedantic#3]
Hello JoAnn,

I wonder why the command line parameter 'uci' is required if the engine is an uci engine anyway. This occurred to me after I forgot to include uci it while installing the engine under Arena and it took me a while to understand why it does not want to move.

Gabor Szots
CCRL testing group

**Comment by JoAnnP38** [comment]
Pedantic supports multiple commands from the command-line. One is, as you noticed, is "uci", but the others are "perft", "label", "learn", and "weights". I probably should have kept things simple and only had one function available from Pedantic, but I was too lazy to create separate executables. Check-out the readme for more information on these commands. Perhaps, I should have named the command "chess", but that is probably not any less confusing.

**Comment by SzotsGabor** [comment]
Thanks for the reply. In the readme I have found only this: "it does support some command-line functionality (more on that later.)"

I'm waiting for that 'later'. :)
