### ISSUE TITLE
Miscellaneous

### ISSUE THREAD

**Issue by SzotsGabor** [JoAnnP38/Pedantic#37]
Version 0.4.1 still displays 0.4.0.

After 'uci' and position 'startpos' the 'go depth <n>' and go infinite commands result in one-line 'bestmove e2e4'.

**Comment by JoAnnP38** [comment]
I was just trying to email you to tell you about 0.4.1. Did you turn off
the book openings? You have to uncheck OwnBook.

**Comment by JoAnnP38** [comment]
Also, I replace the ZIP file with one that now shows the correct version to avoid confusion. I feel horrible about this. I guess it is just too late here. I should have released in the morning.

**Comment by SzotsGabor** [comment]
It's OK now. Actually, removing the bin book from the Pedantic folder is equally good, for CCRL testing we use generic books anyway.

**Comment by JoAnnP38** [comment]
Cool beans. I am so, so, so, sorry for the mix up. I was fixing a bug at the end of the release and I left debugging logic in. Also, I wish we could have a tournament were every engine played its own openings like the old days. But I guess that doesn't work for the upper echelon programs like Stockfish.

**Comment by SzotsGabor** [comment]
Version OK. Book thing also.

No need to worry. We are here to report problems.

Good night.


------ Eredeti üzenet ------
Feladó "JoAnn D. Peeler" ***@***.***>
Címzett "JoAnnP38/Pedantic" ***@***.***>
Másolatot kap "Gabor Szots" ***@***.***>; "Author" 
***@***.***>
Dátum 2023. 08. 04. 9:13:08
Tárgy Re: [JoAnnP38/Pedantic] Miscellaneous (Issue #37)

**Comment by SzotsGabor** [comment]
> I wish we could have a tournament were every engine played its own openings like the old days.

I wonder if authors really build books that matches the style of their engine. Do you?

**Comment by JoAnnP38** [comment]
Original issue no longer a problem.
